export const SHOW_THE_BIRBS       = "SHOW_THE_BIRBS";
export const UPDATE_THE_BIRBS     = "UPDATE_THE_BIRBS";
export const BIRBS_LOADING_STATUS = "BIRBS_LOADING_STATUS";
export const UPDATE_BIRB_FILTER   = "UPDATE_BIRB_FILTER";
export const UPDATE_FILTERED_LIST = "UPDATE_FILTERED_LIST";
export const SHOW_HENLO_CODE      = "SHOW_HENLO_CODE";
export const SHOW_ADD_BIRB        = "SHOW_ADD_BIRB";
export const ADD_NEW_BIRB         = "ADD_NEW_BIRB";